name: "Tests"

on:
    push:

jobs:
    phpunit:
        name:    "Tests"

        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                php-version:
                    - "7.4"
                    - "8.0"
                    - "8.1"
                operating-system:
                    - "ubuntu-latest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    ini-values:  memory_limit=-1
                    tools:       composer:v2

            -   name: "Install dependencies"
                run:  "composer install --no-interaction --no-progress --no-suggest"

            -   name: "Tests"
                run:  "php bin/test.php"
